Introduce comment controller, rework file service
NeHo4y/itmo-kotlin pull request #14
Opened 2021-01-10 17:18 UTC by NeHo4y

2021-01-10 17:51 UTC, dxahtepb requested changes

2021-01-10 17:51 UTC, dxahtepb commented on server/src/main/kotlin/com/github/neho4y/comment/controller/commentController.kt
> +class commentController(private val commentService: CommentService) {
Class name should be in the uppercase

2021-01-10 17:51 UTC, dxahtepb commented on server/src/main/kotlin/com/github/neho4y/comment/model/CommentDto.kt
> +@Serializable
Move this DTOs to the :common project, so we may use it in the Android app

2021-01-10 17:51 UTC, dxahtepb commented on server/src/main/kotlin/com/github/neho4y/file/controller/fileController.kt
> +class fileController(private val fileService: FileService) {
Class name again

2021-01-10 18:45 UTC, dxahtepb approved these changes

2021-01-16 15:01 UTC, maxxkut approved these changes

2021-01-16 15:02 UTC, merged