Implement Category, Topic, Subtopic, Feedback
NeHo4y/itmo-kotlin pull request #4
Opened 2020-11-17 18:55 UTC by maxxkut

2020-11-17 20:04 UTC, NeHo4y approved these changes

2020-11-17 20:54 UTC, dxahtepb requested changes
Looks good! But please do some formatting fixes

2020-11-17 20:54 UTC, dxahtepb commented on server/src/main/kotlin/com/github/neho4y/category/domain/Topic.kt
> +import java.util.*
You have unused imports here and in TopicRepository too

2020-11-17 20:54 UTC, dxahtepb commented on server/src/main/kotlin/com/github/neho4y/category/service/impl/SubtopicServiceImpl.kt
> +        val subtopic = subtopicRepository.findByIdAndIsDeletedFalse(id).orElseThrow();
You forgot the semicolon here

2020-11-17 20:54 UTC, dxahtepb commented on server/src/main/kotlin/com/github/neho4y/category/service/impl/CategoryServiceImpl.kt
> +        private val categoryRepository: CategoryRepository) : CategoryService {
Check class constructor formatting here. If it is multiline, then closing bracket should be on a separate line.

2020-11-17 20:54 UTC, dxahtepb commented on server/src/main/kotlin/com/github/neho4y/feedback/domain/repository/FeedbackRepository.kt
> +interface FeedbackRepository : JpaRepository<Feedback, Long>{
You don't need to write a body for an empty class

2020-11-17 20:54 UTC, dxahtepb commented on server/src/test/kotlin/com/github/neho4y/category/service/CategoryServiceIntegrationTest.kt
> +        val exception = assertThrows<Exception> {
You don't use this variable at all

2020-11-17 20:54 UTC, dxahtepb commented on server/src/test/kotlin/com/github/neho4y/category/service/SubtopicServiceIntegrationTest.kt
> +        categoryRepository.save(category)
You may use `saveAndFlush()` here

2020-11-17 23:48 UTC, dxahtepb commented
Looks like we forgot about methods in services to retrieve all Categories, Topics etc.

2020-11-18 17:47 UTC, dxahtepb requested changes
You forgot methods in services to retrieve all Topics, Categories, etc...

2020-11-18 17:51 UTC, dxahtepb approved these changes

2020-11-18 17:51 UTC, NeHo4y approved these changes

2020-11-18 17:58 UTC, merged

2020-12-07 19:54 UTC, Walingar commented on server/src/main/kotlin/com/github/neho4y/category/model/SubtopicDto.kt
> +
Лишние отступы

2020-12-07 19:54 UTC, Walingar commented on server/src/main/kotlin/com/github/neho4y/category/service/impl/CategoryServiceImpl.kt
> +            throw RuntimeException()
Более специфичное бросать что-то?

2020-12-07 19:54 UTC, Walingar commented on server/src/main/kotlin/com/github/neho4y/feedback/domain/repository/FeedbackRepository.kt
> +interface FeedbackRepository : JpaRepository<Feedback, Long> {
{} не нужны